In [2]:
### NumPy Arrays

In [3]:
my_list = [1,2,3]

In [4]:
import numpy as np

In [5]:
arr = np.array(my_list)

In [6]:
arr

array([1, 2, 3])

In [7]:
my_list_of_list = [[1,2,3], [4,5,6], [7,8,9]]

In [8]:
np.array(my_list_of_list)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [20]:
# linspace third argument is number of data-points, arange third argument is steps

In [16]:
np.linspace(0,5,5)

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [17]:
# identity matrix

In [18]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
# random method, uniform distribution 0 - 1

In [22]:
np.random.rand()

0.776192769658504

In [23]:
np.random.rand(5)

array([0.28027445, 0.23132151, 0.30557079, 0.50435434, 0.81819632])

In [24]:
np.random.rand(5,5)

array([[0.99857822, 0.74807198, 0.72061967, 0.19948055, 0.81925932],
       [0.70600668, 0.97456117, 0.71909477, 0.70550331, 0.87863873],
       [0.81551659, 0.0687175 , 0.7058493 , 0.09425875, 0.2632906 ],
       [0.36304154, 0.04574605, 0.20662677, 0.92321963, 0.2827561 ],
       [0.90995008, 0.23024381, 0.19984136, 0.74782502, 0.01450138]])

In [25]:
# random normal/standard/gaussian distribution centered around 0

In [26]:
np.random.randn(2)

array([-2.12127257,  0.89351339])

In [28]:
np.random.randn(4,4)

array([[-0.77752223,  0.02993719, -0.32257125,  0.39946358],
       [ 0.10304968, -1.02764245, -0.95205296,  0.3348016 ],
       [-0.43035832,  0.2090163 , -0.11485978, -0.70119006],
       [ 2.10367236,  0.54575659, -0.84678605, -0.34003921]])

In [29]:
# random int between low inclusive and high exclusive

In [30]:
np.random.randint(1,100)

25

In [35]:
np.random.randint(1,100,10)

array([30, 38,  7, 90, 23,  7, 82, 67, 10, 70])

In [36]:
# array methods

In [37]:
arr = np.arange(25)

In [38]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [39]:
randarr= np.random.randint(0,50,10)

In [40]:
randarr

array([22,  5, 17, 33, 47, 31,  3, 13, 25, 16])

In [41]:
# reshape method, number of elements must match the new size

In [47]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [48]:
# max, min, index of max, index of min

In [43]:
randarr.max()

47

In [44]:
randarr.min()

3

In [45]:
randarr.argmax()

4

In [46]:
randarr.argmin()

6

In [49]:
# shape of a matrix/vector

In [51]:
arr.shape

(25,)

In [52]:
arr = arr.reshape(5,5)

In [53]:
arr.shape

(5, 5)

In [54]:
# data type of an array

In [55]:
arr.dtype

dtype('int64')

In [56]:
# shortcut import

In [57]:
from numpy.random import randint

In [58]:
randint(2,10)

7