In [2]:
### NumPy Arrays

In [3]:
my_list = [1,2,3]

In [4]:
import numpy as np

In [5]:
arr = np.array(my_list)

In [6]:
arr

array([1, 2, 3])

In [7]:
my_list_of_list = [[1,2,3], [4,5,6], [7,8,9]]

In [8]:
np.array(my_list_of_list)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [20]:
# linspace third argument is number of data-points, arange third argument is steps

In [16]:
np.linspace(0,5,5)

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [17]:
# identity matrix

In [18]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
# random method, uniform distribution 0 - 1

In [22]:
np.random.rand()

0.776192769658504

In [23]:
np.random.rand(5)

array([0.28027445, 0.23132151, 0.30557079, 0.50435434, 0.81819632])

In [24]:
np.random.rand(5,5)

array([[0.99857822, 0.74807198, 0.72061967, 0.19948055, 0.81925932],
       [0.70600668, 0.97456117, 0.71909477, 0.70550331, 0.87863873],
       [0.81551659, 0.0687175 , 0.7058493 , 0.09425875, 0.2632906 ],
       [0.36304154, 0.04574605, 0.20662677, 0.92321963, 0.2827561 ],
       [0.90995008, 0.23024381, 0.19984136, 0.74782502, 0.01450138]])

In [25]:
# random normal/standard/gaussian distribution centered around 0

In [26]:
np.random.randn(2)

array([-2.12127257,  0.89351339])

In [28]:
np.random.randn(4,4)

array([[-0.77752223,  0.02993719, -0.32257125,  0.39946358],
       [ 0.10304968, -1.02764245, -0.95205296,  0.3348016 ],
       [-0.43035832,  0.2090163 , -0.11485978, -0.70119006],
       [ 2.10367236,  0.54575659, -0.84678605, -0.34003921]])

In [29]:
# random int between low inclusive and high exclusive

In [30]:
np.random.randint(1,100)

25

In [35]:
np.random.randint(1,100,10)

array([30, 38,  7, 90, 23,  7, 82, 67, 10, 70])

In [36]:
# array methods

In [37]:
arr = np.arange(25)

In [38]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [39]:
randarr= np.random.randint(0,50,10)

In [40]:
randarr

array([22,  5, 17, 33, 47, 31,  3, 13, 25, 16])

In [41]:
# reshape method, number of elements must match the new size

In [47]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [48]:
# max, min, index of max, index of min

In [43]:
randarr.max()

47

In [44]:
randarr.min()

3

In [45]:
randarr.argmax()

4

In [46]:
randarr.argmin()

6

In [49]:
# shape of a matrix/vector

In [51]:
arr.shape

(25,)

In [52]:
arr = arr.reshape(5,5)

In [53]:
arr.shape

(5, 5)

In [54]:
# data type of an array

In [55]:
arr.dtype

dtype('int64')

In [56]:
# shortcut import

In [57]:
from numpy.random import randint

In [58]:
randint(2,10)

7

In [59]:
# array indexing and selection

In [60]:
arr = np.arange(0,11)

In [61]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
arr[8]

8

In [63]:
arr[1:5]

array([1, 2, 3, 4])

In [64]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [65]:
arr[3:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
arr[0:5] = 100

In [67]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [68]:
arr = np.arange(0,11)

In [69]:
slice_of_arr = arr[0:6]

In [70]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [71]:
slice_of_arr[:] = 999

In [72]:
slice_of_arr

array([999, 999, 999, 999, 999, 999])

In [73]:
arr

array([999, 999, 999, 999, 999, 999,   6,   7,   8,   9,  10])

In [82]:
# slice shows a linked view of the same array to avoid memory issues on large arrays, modification on a slice also modifies the original array

In [75]:
# use copy() instead of slice to have different copy of array

In [76]:
arr = np.arange(0,11)

In [77]:
arr_copy = arr.copy()

In [78]:
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [79]:
arr[0:6] = 1111

In [80]:
arr

array([1111, 1111, 1111, 1111, 1111, 1111,    6,    7,    8,    9,   10])

In [81]:
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [83]:
# matrix (2D Arrays)

In [85]:
arr_2d = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [86]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [87]:
arr_2d[1,1]

5

In [88]:
arr_2d[2,1]

8

In [89]:
arr_2d[0]

array([1, 2, 3])

In [91]:
arr_2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [92]:
arr_2d[2:, 1:]

array([[8, 9]])

In [93]:
# conditional selection

In [94]:
arr = np.arange(1,11)

In [95]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [96]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [97]:
bool_arr = arr > 5

In [98]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [99]:
# returns true only:

In [100]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [101]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [102]:
arr[arr<3]

array([1, 2])

In [103]:
arr[arr<=3]

array([1, 2, 3])

In [104]:
arr[arr>=3]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [105]:
arr_2d = np.arange(50).reshape(5,10)

In [106]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [107]:
arr_2d[arr_2d>=35]

array([35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [108]:
arr_2d[:3, 2:]

array([[ 2,  3,  4,  5,  6,  7,  8,  9],
       [12, 13, 14, 15, 16, 17, 18, 19],
       [22, 23, 24, 25, 26, 27, 28, 29]])

In [110]:
# NumPy Operations (Array with Array, Array with Scalars, Universal Array Functions)

In [111]:
arr = np.arange(0,11)

In [112]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [113]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [114]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [115]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [116]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [117]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [118]:
arr/arr

/Users/sigitp/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [119]:
# nan: not a number 0/0 is not a number

In [120]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [121]:
# universal array functions (ufunc) /math operations, broadcast operations to the entire array

In [122]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [123]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [124]:
np.max(arr)

10

In [125]:
arr.max()

10

In [126]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [127]:
np.log(arr)

/Users/sigitp/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [128]:
# log 0 is neg infinity